// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {evaluator} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function CancelAssistant():Promise<void>;

export function ClearAssistantHistory():Promise<void>;

export function ClearLibCache():Promise<void>;

export function ConfirmDiscard():Promise<boolean>;

export function CreateLibraryFolder(arg1:string):Promise<void>;

export function CreateLocalLibrary(arg1:string,arg2:string):Promise<string>;

export function CreateScratchFile(arg1:string):Promise<string>;

export function Debug(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function DetectAssistantCLIs():Promise<Array<main.CLIInfo>>;

export function DetectSlicers():Promise<Array<main.SlicerInfo>>;

export function ExportMesh(arg1:string):Promise<void>;

export function ForkLibrary(arg1:string,arg2:string):Promise<void>;

export function FormatCode(arg1:string):Promise<string>;

export function GetDebugStepMeshes(arg1:number):Promise<Array<evaluator.DebugMesh>>;

export function GetDefaultSource():Promise<string>;

export function GetDefaultSystemPrompt():Promise<string>;

export function GetDocGuides():Promise<Array<main.DocGuide>>;

export function GetExample(arg1:string):Promise<string>;

export function GetExampleList():Promise<Array<string>>;

export function GetLibraryDir():Promise<string>;

export function GetLibraryFilePath(arg1:string):Promise<string>;

export function GetLogDir():Promise<string>;

export function GetMemoryLimit():Promise<number>;

export function GetSettings():Promise<string>;

export function GetStderrLog():Promise<string>;

export function InstallLibrary(arg1:string,arg2:string):Promise<void>;

export function IsScratchFile(arg1:string):Promise<boolean>;

export function ListLibraries():Promise<Array<main.LibraryInfo>>;

export function ListLibraryFolders():Promise<Array<string>>;

export function ListLocalLibraries():Promise<Array<main.LibraryInfo>>;

export function MemStats():Promise<Record<string, number>>;

export function OpenFile():Promise<Record<string, string>>;

export function OpenLibraryDir(arg1:string):Promise<Record<string, string>>;

export function OpenRecentFile(arg1:string):Promise<Record<string, string>>;

export function PatchSettings(arg1:string):Promise<void>;

export function PickImageFile():Promise<string>;

export function PruneSources(arg1:Array<string>):Promise<void>;

export function PullAllLibraries():Promise<void>;

export function ResetRunner():Promise<void>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function Run(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function RunGC():Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SendAssistantMessage(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SendToSlicer(arg1:string):Promise<void>;

export function SetAssistantConfig(arg1:main.AssistantConfig):Promise<void>;

export function SetDirtyState(arg1:boolean):Promise<void>;

export function SetMemoryLimit(arg1:number):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function Stop():Promise<void>;

export function UpdateLibrary(arg1:string,arg2:string):Promise<void>;

export function UpdateSource(arg1:string,arg2:string):Promise<void>;
