// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function CancelAssistant() {
  return window['go']['main']['App']['CancelAssistant']();
}

export function ClearAssistantHistory() {
  return window['go']['main']['App']['ClearAssistantHistory']();
}

export function ClearLibCache() {
  return window['go']['main']['App']['ClearLibCache']();
}

export function ConfirmDiscard() {
  return window['go']['main']['App']['ConfirmDiscard']();
}

export function CreateLibraryFolder(arg1) {
  return window['go']['main']['App']['CreateLibraryFolder'](arg1);
}

export function CreateLocalLibrary(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalLibrary'](arg1, arg2);
}

export function CreateScratchFile(arg1) {
  return window['go']['main']['App']['CreateScratchFile'](arg1);
}

export function Debug(arg1, arg2, arg3) {
  return window['go']['main']['App']['Debug'](arg1, arg2, arg3);
}

export function DeleteScratchFile(arg1) {
  return window['go']['main']['App']['DeleteScratchFile'](arg1);
}

export function DetectAssistantCLIs() {
  return window['go']['main']['App']['DetectAssistantCLIs']();
}

export function DetectSlicers() {
  return window['go']['main']['App']['DetectSlicers']();
}

export function ExportMesh(arg1) {
  return window['go']['main']['App']['ExportMesh'](arg1);
}

export function ForkLibrary(arg1, arg2) {
  return window['go']['main']['App']['ForkLibrary'](arg1, arg2);
}

export function FormatCode(arg1) {
  return window['go']['main']['App']['FormatCode'](arg1);
}

export function GetAssistantAvailable() {
  return window['go']['main']['App']['GetAssistantAvailable']();
}

export function GetAssistantConfig() {
  return window['go']['main']['App']['GetAssistantConfig']();
}

export function GetDebugStepMeshes(arg1) {
  return window['go']['main']['App']['GetDebugStepMeshes'](arg1);
}

export function GetDefaultSource() {
  return window['go']['main']['App']['GetDefaultSource']();
}

export function GetDefaultSystemPrompt() {
  return window['go']['main']['App']['GetDefaultSystemPrompt']();
}

export function GetDocGuides() {
  return window['go']['main']['App']['GetDocGuides']();
}

export function GetExample(arg1) {
  return window['go']['main']['App']['GetExample'](arg1);
}

export function GetExampleList() {
  return window['go']['main']['App']['GetExampleList']();
}

export function GetLastFile() {
  return window['go']['main']['App']['GetLastFile']();
}

export function GetLibraryDir() {
  return window['go']['main']['App']['GetLibraryDir']();
}

export function GetLibraryFilePath(arg1) {
  return window['go']['main']['App']['GetLibraryFilePath'](arg1);
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetMemoryLimit() {
  return window['go']['main']['App']['GetMemoryLimit']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStderrLog() {
  return window['go']['main']['App']['GetStderrLog']();
}

export function InstallLibrary(arg1, arg2) {
  return window['go']['main']['App']['InstallLibrary'](arg1, arg2);
}

export function IsReadOnlyPath(arg1) {
  return window['go']['main']['App']['IsReadOnlyPath'](arg1);
}

export function IsScratchFile(arg1) {
  return window['go']['main']['App']['IsScratchFile'](arg1);
}

export function ListLibraries() {
  return window['go']['main']['App']['ListLibraries']();
}

export function ListLibraryFolders() {
  return window['go']['main']['App']['ListLibraryFolders']();
}

export function ListLocalLibraries() {
  return window['go']['main']['App']['ListLocalLibraries']();
}

export function MemStats() {
  return window['go']['main']['App']['MemStats']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenLibraryDir(arg1) {
  return window['go']['main']['App']['OpenLibraryDir'](arg1);
}

export function OpenRecentFile(arg1) {
  return window['go']['main']['App']['OpenRecentFile'](arg1);
}

export function PatchSettings(arg1) {
  return window['go']['main']['App']['PatchSettings'](arg1);
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function PullAllLibraries() {
  return window['go']['main']['App']['PullAllLibraries']();
}

export function RekeySource(arg1, arg2) {
  return window['go']['main']['App']['RekeySource'](arg1, arg2);
}

export function RemoveLibrary(arg1, arg2) {
  return window['go']['main']['App']['RemoveLibrary'](arg1, arg2);
}

export function RemoveLocalLibrary(arg1) {
  return window['go']['main']['App']['RemoveLocalLibrary'](arg1);
}

export function ResetRunner() {
  return window['go']['main']['App']['ResetRunner']();
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function Run(arg1, arg2, arg3) {
  return window['go']['main']['App']['Run'](arg1, arg2, arg3);
}

export function RunGC() {
  return window['go']['main']['App']['RunGC']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveScreenshot(arg1) {
  return window['go']['main']['App']['SaveScreenshot'](arg1);
}

export function SendAssistantMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendAssistantMessage'](arg1, arg2, arg3, arg4);
}

export function SendToSlicer(arg1) {
  return window['go']['main']['App']['SendToSlicer'](arg1);
}

export function SetAssistantConfig(arg1) {
  return window['go']['main']['App']['SetAssistantConfig'](arg1);
}

export function SetLastFile(arg1) {
  return window['go']['main']['App']['SetLastFile'](arg1);
}

export function SetMemoryLimit(arg1) {
  return window['go']['main']['App']['SetMemoryLimit'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function UpdateLibrary(arg1, arg2) {
  return window['go']['main']['App']['UpdateLibrary'](arg1, arg2);
}

export function UpdateSource(arg1, arg2) {
  return window['go']['main']['App']['UpdateSource'](arg1, arg2);
}
