#!/usr/bin/env bash
# Generate stub files at desktop/frontend/wailsjs/{go/main/App.{js,d.ts},
# runtime/runtime.{js,d.ts},go/models.ts}. The real files are produced by
# `wails build` from the Go App struct; this script produces minimal shims
# sufficient to satisfy vite's module resolution so the frontend integration
# tests can run in CI without Go/Wails installed. At runtime, the test harness
# mocks every Wails method via a Proxy on window.go.main.App, so the stub
# function bodies are never actually invoked.
#
# Names are scraped out of `import { ... } from '../wailsjs/...'` lines in
# src/ — that's the contract between src/ and wailsjs/. New imports added to
# src/ are picked up automatically on the next CI run; no manual sync needed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$REPO_ROOT/desktop/frontend/src"
OUT_DIR="$REPO_ROOT/desktop/frontend/wailsjs"

mkdir -p "$OUT_DIR/go/main" "$OUT_DIR/runtime"

# Use a temp perl script to avoid bash quoting hell.
PERL_SCRIPT="$(mktemp)"
trap 'rm -f "$PERL_SCRIPT"' EXIT

cat > "$PERL_SCRIPT" <<'PERLEOF'
my $suffix = shift @ARGV;
my $blob = do { local $/; <STDIN> };
# Note: use / as the regex delimiter so { and } inside character classes
# don't need escaping. m{...} would terminate the regex at the } in [^}].
while ($blob =~ /import\s*\{\s*([^}]+?)\s*\}\s*from\s*['"]([^'"]+)['"]/gs) {
    my ($names, $path) = ($1, $2);
    next unless $path =~ /\Q$suffix\E$/;
    for my $n (split /[\s,]+/, $names) {
        next unless $n =~ /^[A-Za-z_][A-Za-z0-9_]*$/;
        print "$n\n";
    }
}
PERLEOF

extract_named_imports() {
    cat "$SRC_DIR"/*.ts | perl "$PERL_SCRIPT" "$1" | sort -u
}

APP_NAMES=()
while IFS= read -r name; do APP_NAMES+=("$name"); done < <(extract_named_imports "/wailsjs/go/main/App")

RT_NAMES=()
while IFS= read -r name; do RT_NAMES+=("$name"); done < <(extract_named_imports "/wailsjs/runtime/runtime")

# wailsjs/go/main/App — bound to window.go.main.App at runtime.
{
    echo "// AUTOGENERATED stub — see scripts/gen-wailsjs-stubs.sh"
    for name in "${APP_NAMES[@]}"; do
        echo "export function $name(...args) { return window['go']['main']['App']['$name'](...args); }"
    done
} > "$OUT_DIR/go/main/App.js"
{
    echo "// AUTOGENERATED stub — see scripts/gen-wailsjs-stubs.sh"
    for name in "${APP_NAMES[@]}"; do
        echo "export function $name(...args: any[]): Promise<any>;"
    done
} > "$OUT_DIR/go/main/App.d.ts"

# wailsjs/runtime/runtime — bound to window.runtime, not window.go.main.App.
{
    echo "// AUTOGENERATED stub — see scripts/gen-wailsjs-stubs.sh"
    for name in "${RT_NAMES[@]}"; do
        echo "export function $name(...args) { return window['runtime']['$name'](...args); }"
    done
} > "$OUT_DIR/runtime/runtime.js"
{
    echo "// AUTOGENERATED stub — see scripts/gen-wailsjs-stubs.sh"
    for name in "${RT_NAMES[@]}"; do
        echo "export function $name(...args: any[]): any;"
    done
} > "$OUT_DIR/runtime/runtime.d.ts"

# wailsjs/go/models.ts — real Wails emits typed namespaces here; the
# integration tests don't reference any model types, so an empty namespace
# stub keeps any tsc paths happy.
cat > "$OUT_DIR/go/models.ts" <<'MODEOF'
// AUTOGENERATED stub — see scripts/gen-wailsjs-stubs.sh
export namespace main {}
MODEOF

echo "Generated ${#APP_NAMES[@]} App stubs and ${#RT_NAMES[@]} runtime stubs in $OUT_DIR"
